---
title: "project_final"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(plotly)
library(gganimate)
library(ggthemes)
library(shiny)

library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(plotly)
library(gganimate)
library(ggthemes)
library(rsconnect)
library(scales)
library(ggtext)
```


Reading in:

```{r, echo=FALSE}
health <- read_csv("heart_2020_cleaned.csv")
```

```{r, echo=FALSE}
bmi_groups <- health %>% 
  clean_names() %>% 
  mutate(bmi_group=case_when(bmi<18.5~"Underweight",
                         bmi>=18.5 & bmi<=24.9~"Normal Weight",
                         bmi>=25 & bmi<=29.9~"Overweight",
                         bmi>=30 & bmi<=34.9~"Obesity Class I",
                         bmi>=35 & bmi<=35.9~"Obesity Class II",
                         bmi>=36~"Extreme Obesity"))

```

```{r,echo=FALSE, show_col_types = FALSE}
weight <- 73
height <- 171

dataset <- tibble(weight,
                  height) %>% 
  mutate(BMI_val = weight/((height/100)^2),
         bmi_cat = case_when(BMI_val<18.5~"Underweight",
                         BMI_val>=18.5 & BMI_val<25~"Normal Weight",
                         BMI_val>=25 & BMI_val<30~"Overweight",
                         BMI_val>=30 & BMI_val<35~"Obesity Class I",
                         BMI_val>=35 & BMI_val<36~"Obesity Class II",
                         BMI_val>=36~"Extreme Obesity")) 
user_bmi <- dataset$bmi_cat

dataset

bmi_groups %>% 
  clean_names() %>% 
  filter(bmi_group == user_bmi,
         sex == "Female",
         age_category == "18-24",
         physical_activity == "No") %>% 
  summarize(heart_disease_prevalence =  (sum(heart_disease == "Yes")/n())*100,
            no_heart_disease = (sum(heart_disease == "No")/n())*100)
```

```{r,echo=FALSE, show_col_types = FALSE}
table(bmi_groups$gen_health)
```

User manual:

Please input your weight in kilograms and height in centimeters. Select whether you exercise and/or smoke. Click on the button once you are ready to find out the percentage of surveyed people of similar characteristics to those indicated by you who suffer from heart disease. 


```{r, echo=FALSE, show_col_types = FALSE}
 #Reading the dataset 

health <- read_csv("heart_2020_cleaned.csv")

#Data
bmi_groups <- health %>% 
  clean_names() %>% 
  mutate(bmi_group=case_when(bmi<18.5~"Underweight",
                             bmi>=18.5 & bmi<=24.9~"Normal Weight",
                             bmi>=25 & bmi<=29.9~"Overweight",
                             bmi>=30 & bmi<=34.9~"Obesity Class I",
                             bmi>=35 & bmi<=35.9~"Obesity Class II",
                             bmi>=36~"Extreme Obesity"))
```



```{r, echo=FALSE, show_col_types = FALSE}
shinyApp(

ui = fluidPage(
  sidebarLayout(
  sidebarPanel(
    numericInput(inputId = "weight",
               label = "Weight (Kg)",
               value = "65"),
  numericInput(inputId = "height",
               label = "Height (Cm)",
               value = "170"),
  selectInput(inputId = "sex",
               label = "Sex",
               choices = list(Female = "Female", Male = "Male")),
  selectInput(inputId = "age_cat",
               label = "Age Category",
               choices = bmi_groups %>% 
                 arrange(age_category) %>% 
                 distinct(age_category) %>% 
                 pull(age_category),
               multiple=FALSE),
  selectInput(inputId = "phys_act",
               label = "Physical Activity",
               choices = list(Yes = "Yes", No = "No")),
  selectInput(inputId = "smoking",
              label = "Smoke",
              choices = list(Yes = "Yes", No = "No")),
  submitButton(text="Ready!")),
  mainPanel(
    plotOutput(outputId = "Percentage_plot")
  ))),


server=function(input,output){
 
  output$Percentage_plot <- renderPlot({
   
    
    weight <- input$weight
    height <- input$height
    
    dataset <- tibble(weight,
                      height) %>%
      mutate(BMI_val = weight/((height/100)^2),
             bmi_cat = case_when(BMI_val<18.5~"Underweight",
                                 BMI_val>=18.5 & BMI_val<25~"Normal Weight",
                                 BMI_val>=25 & BMI_val<30~"Overweight",
                                 BMI_val>=30 & BMI_val<35~"Obesity Class I",
                                 BMI_val>=35 & BMI_val<36~"Obesity Class II",
                                 BMI_val>=36~"Extreme Obesity")) 
    user_bmi <- dataset$bmi_cat
    
    app_data <- bmi_groups %>%
      filter(bmi_group == user_bmi,
             sex == input$sex,
             age_category == input$age_cat,
             physical_activity == input$phys_act,
             smoking == input$smoking) %>% 
      group_by(heart_disease) %>% 
      mutate(count_per_HDPrevalence= n()) %>% 
      ungroup() %>% 
      mutate(total= n(),
             prop= (count_per_HDPrevalence/total))
  
    
    bar_distribution <- app_data%>%
      ggplot()+
      geom_bar(aes(x=1, fill = heart_disease), position = "fill",show.legend = FALSE)+
      theme_clean()
    
    pie <- bar_distribution +
      coord_polar("y", start= 0)+
      scale_fill_brewer(palette="Pastel1")+
      theme_void()+
      geom_text(aes(x= 1, y= prop/1.5, label= scales::percent(prop, accuracy = 0.01)))+
      labs(x= NULL,
           y= NULL,
           title= "Percentage of Population of Similar Characteristics <span style = 'color: lightblue2;'>with Heart Disease</span>",
           caption = "User manual:\n 
           Please input your weight in kilograms and height in centimeters. Select your age category and whether you exercise and/or smoke.\n
           Click on the button once you are ready to find out the percentage of surveyed people of similar characteristics to those indicated\n by you who suffer from heart disease.")+
      theme(plot.title = element_markdown())

    pie
  })
}
)
```

